### PR TITLE
localise currencies | fixes #61

### LINKED ISSUE #61: Small translation error
The name for "Datos recuperados" returns  the name in English "Salvaged Data". I don't think it would be intended so that why I'm creating this.
Captura de pantalla 2023-12-30 180814

### PR DESCRIPTION
**Pull request by Lenni009**
Might be a quick'n'dirty implementation 😅 
I just smashed on my keyboard until it magically worked haha

fixes #61

### CODE REVIEW

**Comment by Khaoz-Topsy** [comment]
Very cool! Do the item names need their first letter capitalised though? 🤔

**Comment by Lenni009** [comment]
Would you rather have it say "UNITS" and "QUICKSILVER"?

**Comment by Khaoz-Topsy** [comment]
Ah... So it is more a function to make sure everything except the first character is lowercase 😂. I wonder why HG did it that way 🤔

**Review by Khaoz-Topsy — APPROVED** [review]

**Comment by Lenni009** [comment]
UNITS and QUICKSILVER are technically not items the player can obtain. They still localised their caps versions though, for example in German it's QUECKSILBER

**Pull request merged**
